### ISSUE TITLE
Update AttributeInspectorSkin to use ESRI Flex API 3.6

### ISSUE THREAD

**Issue by quick6black** [lheberlie/building-mobile-apps-flex#16]
run into an actionscript error on "Required skin part rangeDomain Field cannot be found" when trying to edit a feature using the new ESRI Flex API 3.4.  Yann Carbon provides a solution on this post http://forums.arcgis.com/threads/84227-Create-an-infowindow-in-a-flex-mobile-project?p=323707&viewfull=1#post323707 but it may not pertain to this application.

**Comment by quick6black** [comment]
compiled on the ESRI Flex API 3.5, same result

**Comment by quick6black** [comment]
is this project totally dead?

**Comment by lheberlie** [comment]
Updated to support version 3.6 of ArcGIS API for Flex

**Comment by quick6black** [comment]
thank you
