### ISSUE TITLE
How to accommodate multiple screens

### ISSUE THREAD

**Issue by yakiler** [lheberlie/building-mobile-apps-flex#18]
Hi
      When I was using flex to learn how to develop mobile applications, I didn't quite understand how to adapt to multiple resolution screens.I see a bitmap that can be adaptive by setting multiple dpi, but where is the layout of the component (width and location)? 
       I look forward to your help and thank you very much

**Comment by neminovno** [comment]
@yakiler Set it where is the component defined.. in MXML I guess. Check [this code](https://github.com/lheberlie/building-mobile-apps-flex/blob/develop/samples/hello-css-media-queries/src/views/HelloMediaQueriesHomeView.mxml#L101-L109) as example.

Try asking on [Apache Flex Users forum](http://apache-flex-users.2333346.n4.nabble.com/). 
Maybe this post can help: [MultiDPIBitmapSource multiple use](http://apache-flex-users.2333346.n4.nabble.com/MultiDPIBitmapSource-multiple-use-td15275.html)

**Comment by lheberlie** [comment]
thanks @yakiler

**Comment by yakiler** [comment]
I started to understand, thanks again
